### ISSUE TITLE
Test example?

### ISSUE THREAD

**Issue by BruceNielsen** [komorra/NodeEditorWinforms#1]
Any chance of a runnable test example? As it stands there's bits missing from the example usage code to get it to do anything: 
Error   CS0535  'FContext' does not implement interface member 'INodesContext.FeedbackInfo' etc.

**Comment by komorra** [comment]
You are correct. At minimum implementation of INodesContext derived class should contain following members actually:
`public NodeVisual CurrentProcessingNode { get; set; }
public event Action<string, NodeVisual, FeedbackType, object, bool> FeedbackInfo;`
Thank you for reminding me about this :) (I'm also updated Readme.md of the project).

**Comment by olivernovakovic** [comment]
Thanks a lot for your work and providing the source code. I second Bruce's request:
A runable test example would be very helpful to quickly test your library / control and to get things up and running faster.
Thanks again!

**Comment by komorra** [comment]
Hi, the samples will be added soon (today probbably), but it will bring some small project structure changes (moving .csproj into the inside folder, adding sln, adding sample projects). Thanks for the request, and stay tuned :)

**Comment by komorra** [comment]
Hello again, now I'm added working example (math nodes), that you could check for basic usage of the framework, hope this will be useful. In the future I'm planning to add more complex examples.

**Comment by olivernovakovic** [comment]
Hi komorra, thank you very much for the update. This is very helpful. 
I have just looked into the MathSample and it seems like a very good starting point.
Great work!

**Comment by TurkerTunali** [comment]
I am considering to use komorra for executing our BPM rules. I am evaluating right now. It seems very mature and capable. I hope I will use it.
