### ISSUE TITLE
Node Width

### ISSUE THREAD

**Issue by kiranmaya** [komorra/NodeEditorWinforms#12]
How to Set node Width ?

**Comment by kiranmaya** [comment]
Thanks you for sharing this awesome node editor .
Before implementation of nodes ,changing and compiling each time a value change take lot of time , and its so discouraging to modify scripts ,now with nodes everything is fast and easy . 
![NodesLogic](https://user-images.githubusercontent.com/3712631/68250427-e81ac280-0046-11ea-8f9a-152085501bf1.png)

**Comment by kiranmaya** [comment]
can you give an example of custom editor for nodes

**Comment by komorra** [comment]
> How to Set node Width ?

Feature of a custom node with and height was added from commit d889db48aa2a26f2642b40285351f05988e885e2 (24 Jan 2021). Now it can be used for example:

```cs
[Node("IsPrime",isCallable:false, width:250)]
public void IsPrime(int number, out bool result)
{
    result = true;
    for (int i = 2; i < Math.Sqrt(number)+1; i++)
    {
        if(number % i == 0)
        {
            result = false;
        }
    }
}
```

**Comment by kiranmaya** [comment]
Thanks for the feature.
