### ISSUE TITLE
Error when "out string" is used

### ISSUE THREAD

**Issue by TurkerTunali** [komorra/NodeEditorWinforms#2]
Hello,

If we use string parameter as output we get error on control. 
![pasted image at 2016_12_28 09_50 am](https://cloud.githubusercontent.com/assets/710051/21515790/c1254b62-cce3-11e6-9c85-36e31a7418cc.png)

What can we do about it?

Code Example:
`
[Node("XML Data", "Input", "Basic", "Allows to output a XML value.",false)]
public void InputXml(string inValue, out string outValue)
        {
            outValue = inValue;
            string strOut = "";
            //MessageBox("strOut");
        }
`

**Comment by komorra** [comment]
Hello,

Please enable C# Exception Handling (full check on "Common Language Runtime Exceptions"), and try to break on the moment that exception occurs. Please provide here more detail on exception and inner exception as well then.

**Comment by TurkerTunali** [comment]
We have added this line to resolve issue before your comment. Next time we will try to give exception as well.

var p = output.ParameterType == typeof(string) ? "" :
                        **output.ParameterType.FullName.Replace("&", "").Replace(" ", "") == "System.String" ? ""** :
                       Activator.CreateInstance(AppDomain.CurrentDomain, output.ParameterType.Assembly.GetName().Name,
                            output.ParameterType.FullName.Replace("&", "").Replace(" ", "")).Unwrap();
