### ISSUE TITLE
Zooming and mouse control enhancements

### ISSUE THREAD

**Issue by milnet92** [komorra/NodeEditorWinforms#20]
First of all, great work on this! I've been willing to include this into one of my projects, and I am thinking to contribute a little bit with the following:

- Zooming: Allow the consumer to set the zooming level (zoom on and out). Setting default to 1f for 100% zooming level. I'm thinking it would be good if the control does it automatically for you when you use the wheel but also allow you invalidate it and set it manually throw a ZoomLevel property.

- Move through the control using mouse drag: When you press Alt + Click, you enter now into Drag mode, where the cursor is changed to a grabbing hand and allow you to move thorugh the graph without scrolling. Stop pressing Alt and you will stop this behaviour.

Let me know if the project is open to contributions and how.

Thank you.

**Comment by komorra** [comment]
Please see: https://github.com/komorra/NodeEditorWinforms/commit/91ebdfd3647da2a022e9eca3227958a9311cfc23 , personally  I thinking of to archive this project in the near future (i have no time to enhace it - in the current shape).
