### ISSUE TITLE
AssemblyResolver can't find the Assembly [NodesControl.cs]

### ISSUE THREAD

**Issue by sqrMin1** [komorra/NodeEditorWinforms#8]
I found an issue in the AssemblyResolver here:
https://github.com/komorra/NodeEditorWinforms/blob/master/NodeEditor/NodesControl.cs#L368

`x => x.GetName() == assemblyName` this compares two different physical identities of assemblies, which returns 'null' as a result.

To resolve this issue you just need to compare their **Assembly.FullNames** like this:

`x => x.GetName().ToString() == assemblyName.FullName;`

---

I was trying to connect two identical List sockets, but the connection failed. After applying the above mentioned fix, it is possible to work with generic Lists in the NodeGraph, as the AssemblyResolver will find the correct connected Assembly.

Are you accepting pull request? Then I could do it for you if wished.

BTW: NodeEditorWinforms is very nice. You did a great job. Thank you!

**Comment by komorra** [comment]
@sqrMin1 Thank you :) After a "while" it is fixed by f6d5e834320c827726d5f5f3ffc496fa403a01b5
